<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <TestProjectType>UnitTest</TestProjectType>
    <AssemblyTitle>RealTimeTests</AssemblyTitle>
    <Company>dymanoid</Company>
    <Product>RealTime</Product>
    <Description>Unit tests for the Real Time mods</Description>
    <Copyright>Copyright © 2018, dymanoid</Copyright>
    <OutputPath>..\bin\Tests\$(Configuration)\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RealTime\RealTime.csproj" />
    <Reference Include="UnityEngine">
      <HintPath>$(CitiesSkylinesBinaries)UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <TestRuntimeGameAssembly Include="$(CitiesSkylinesBinaries)Assembly-CSharp.dll" />
    <TestRuntimeGameAssembly Include="$(CitiesSkylinesBinaries)ColossalManaged.dll" />
    <TestRuntimeGameAssembly Include="$(CitiesSkylinesBinaries)ICities.dll" />
    <TestRuntimeGameAssembly Include="$(CitiesSkylinesBinaries)UnityEngine.dll" />
    <TestRuntimeGameAssembly Include="$(CitiesSkylinesBinaries)UnityEngine.UI.dll" />
  </ItemGroup>
  <Target Name="CopyCitiesSkylinesTestRuntimeAssemblies" AfterTargets="Build">
    <Copy
      SourceFiles="@(TestRuntimeGameAssembly)"
      DestinationFolder="$(OutputPath)"
      SkipUnchangedFiles="true" />
  </Target>
</Project>
